### ISSUE TITLE
请教一下，应该用什么版本的python呢？

### ISSUE THREAD

**Issue by Kline-song** [GDDG08/YanHeKT_Downloader#3]
我使用python3和python2都会报一些语法错误或者是依赖模块的错误，可以请教一下应该用什么版本的python呢？
当然也有可能跟python版本没有关系，只是我的操作出现了一些问题。

**Comment by HansZ8** [comment]
这个脚本语法很简单，应该3.6+都能用的。
可能你没有安装依赖，请在命令行使用
`pip install -r requirements.txt`
如果还有其他问题，请附上报错，谢谢！

**Comment by HansZ8** [comment]
最新版本已支持`python3.12`
